apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: looply
  labels:
    app: client-service
    tier: frontend-service
spec:
  type: ClusterIP
  selector:
    app: client
    tier: frontend
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
