# This is for dev environment
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: looply
  labels:
    app: server-secret
    tier: backend-secret
type: Opaque
data:
  TEST: "test_value"
