apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: looply
  labels:
    app: server-service
    tier: backend-service
spec:
  type: ClusterIP
  selector:
    app: server
    tier: backend
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
